# Generated by Django 4.2 on 2023-06-12 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("founder", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField()),
                ("services_offered", models.TextField()),
                ("logo", models.TextField()),
                (
                    "year_established",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("employees", models.IntegerField(default=0)),
                ("valuation", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "company_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("employees_required", models.IntegerField(default=0)),
                ("skills_req", models.TextField()),
                ("time_tobe_dedicated", models.TextField()),
                ("pay", models.TextField()),
                ("duration", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.TextField(blank=True)),
                (
                    "comapny",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corposhare.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("profile_pic", models.TextField()),
                ("age", models.IntegerField(default=18)),
                ("sex", models.CharField(blank=True, max_length=200, null=True)),
                ("education", models.CharField(blank=True, max_length=200, null=True)),
                ("skills", models.TextField()),
                ("experience", models.IntegerField(default=1)),
                ("address1", models.CharField(blank=True, max_length=200, null=True)),
                ("address2", models.CharField(blank=True, max_length=200, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=200, null=True)),
                ("resume", models.TextField()),
                ("department", models.TextField()),
                ("contact", models.CharField(blank=True, max_length=200, null=True)),
                ("hire_date", models.DateField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corposhare.company",
                    ),
                ),
            ],
        ),
    ]
